lane :build_for_hockey do |options|
  prepare_environment

  cert(username: ENV['ITUNES_CONNECT_USERNAME'], team_id: options[:dp_team_id])
  sigh(app_identifier: "io.horizontalsystems.LightningWallet", force: true, adhoc: true, username: ENV['ITUNES_CONNECT_USERNAME'], team_id: options[:dp_team_id])
  gym(scheme: "LightningWallet", export_method: "ad-hoc", silent: true, clean: true, export_options: { compileBitcode: false })

  upload_to_app_center(options[:app_center_api_token])
end

def prepare_environment
  sh("rm -rf ~/Library/Developer/Xcode/Archives/**")
  sh("rm -rf ~/Library/MobileDevice/Provisioning\\ Profiles/**")

  reset_git_repo(force: true)
  clear_derived_data

  increment_build_number_in_plist(
    build_number: ENV['BUILD_NUMBER']
  )

  cocoapods(repo_update: true)
end

def upload_to_app_center(api_token)
  appcenter_upload(
    api_token: api_token,
    owner_name: "Horizontal-Systems",
    owner_type: "organization",
    app_name: "Lightning-Wallet",
    notify_testers: true,
    release_notes: last_git_commit[:message]
  )
end
